# Generated by Django 2.0.5 on 2019-11-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='region',
            field=models.SmallIntegerField(choices=[(1, '中国大陆'), (2, '港台'), (3, '欧美'), (4, '其他'), (5, '未知')], default=5, max_length=10),
        ),
    ]
