# Generated by Django 2.0.5 on 2019-11-04 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20191103_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('num', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-num',),
            },
        ),
        migrations.AlterField(
            model_name='singer',
            name='region',
            field=models.SmallIntegerField(choices=[(1, '中国大陆'), (2, '港台'), (3, '欧美'), (4, '其他'), (5, '未知')], default=5),
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='song.Singer'),
        ),
        migrations.AddField(
            model_name='song',
            name='tags',
            field=models.ManyToManyField(related_name='related_songs', to='song.Tag'),
        ),
    ]
