# Generated by Django 2.0.5 on 2019-11-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20191104_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, upload_to='song_files'),
        ),
    ]
