# Generated by Django 2.0.5 on 2019-11-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_auto_20191104_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='poster',
            field=models.ImageField(blank=True, upload_to='song_files/poster'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, upload_to='song_files/audio'),
        ),
    ]
