# Generated by Django 2.0.5 on 2019-11-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_remove_singer_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='num',
            field=models.IntegerField(default=1),
        ),
    ]
